# Generated by Django 6.1 on 2026-09-07 16:41

"""Prepara las tablas de áreas, cargos, perfiles y asignaciones de psicólogos.

Este paso ya está aplicado; solo se actualiza su explicación.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'área institucional',
                'verbose_name_plural': 'áreas institucionales',
                'db_table': 'saspel_area_institucional',
            },
        ),
        migrations.CreateModel(
            name='CargoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cargo institucional',
                'verbose_name_plural': 'cargos institucionales',
                'db_table': 'saspel_cargo_institucional',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=50, unique=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=150)),
                ('nombre_preferido', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tamizaje_resuelto', models.BooleanField(default=False)),
                ('habilitado_asignaciones', models.BooleanField(default=True, help_text='Permite recibir nuevas asignaciones sin cambiar el estado del usuario.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='api.areainstitucional')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='api.cargoinstitucional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'db_table': 'saspel_perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='AsignacionProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('REASIGNADA', 'Reasignada')], default='ACTIVA', max_length=10)),
                ('motivo_fin', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_como_psicologo', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_como_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación profesional',
                'verbose_name_plural': 'asignaciones profesionales',
                'db_table': 'saspel_asignacion_profesional',
                'constraints': [models.CheckConstraint(condition=models.Q(('trabajador', models.F('psicologo')), _negated=True), name='saspel_asignacion_usuarios_distintos'), models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('trabajador',), name='saspel_una_asignacion_activa_por_trabajador'), models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVA', 'FINALIZADA', 'REASIGNADA'])), name='saspel_asignacion_estado_valido')],
            },
        ),
    ]
