# Generated by Django 6.1 on 2026-09-07 16:41

"""Asegura que existan los cinco grupos de usuarios de SASPEL sin duplicarlos.

No crea usuarios ni asigna permisos. Al revertir este paso se conservan los
grupos para no perder sus miembros.
"""

from django.db import migrations


ROLES = ('NUEVO_TRABAJADOR', 'TRABAJADOR', 'PSICOLOGO', 'ADMIN', 'SUPERADMIN')


def crear_roles(apps, schema_editor):
    """Crea los grupos que falten y conserva los que ya existen."""
    Group = apps.get_model('auth', 'Group')
    for nombre in ROLES:
        Group.objects.using(schema_editor.connection.alias).get_or_create(name=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Al revertir, conserva los grupos y las personas que ya pertenecen a ellos.
        migrations.RunPython(crear_roles, reverse_code=migrations.RunPython.noop),
    ]
