# Generated by Django 6.1 on 2026-09-07 16:56

"""Prepara las nueve tablas de cuestionarios, preguntas, respuestas y resultados.

No carga cuestionarios reales. Este paso ya está aplicado; solo cambia su
explicación.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crear_roles_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'escala de respuesta',
                'verbose_name_plural': 'escalas de respuesta',
                'db_table': 'saspel_escala_respuesta',
            },
        ),
        migrations.CreateModel(
            name='AsignacionInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('SISTEMA', 'Sistema'), ('PROFESIONAL', 'Profesional')], max_length=11)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=11)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_de_instrumentos_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_de_instrumentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación de instrumento',
                'verbose_name_plural': 'asignaciones de instrumentos',
                'db_table': 'saspel_asignacion_instrumento',
            },
        ),
        migrations.CreateModel(
            name='AplicacionInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada'), ('ANULADA', 'Anulada')], default='INICIADA', max_length=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacion', to='api.asignacioninstrumento')),
            ],
            options={
                'verbose_name': 'aplicación de instrumento',
                'verbose_name_plural': 'aplicaciones de instrumentos',
                'db_table': 'saspel_aplicacion_instrumento',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('es_inicial', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instrumento psicológico',
                'verbose_name_plural': 'instrumentos psicológicos',
                'db_table': 'saspel_instrumento_psicologico',
                'constraints': [models.UniqueConstraint(fields=('codigo', 'version'), name='saspel_instrumento_codigo_version_unico')],
            },
        ),
        migrations.AddField(
            model_name='asignacioninstrumento',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='api.instrumentopsicologico'),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=150)),
                ('valor', models.SmallIntegerField()),
                ('orden', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='api.escalarespuesta')),
            ],
            options={
                'verbose_name': 'opción de respuesta',
                'verbose_name_plural': 'opciones de respuesta',
                'db_table': 'saspel_opcion_respuesta',
            },
        ),
        migrations.CreateModel(
            name='PreguntaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo_respuesta', models.CharField(choices=[('ESCALA', 'Escala'), ('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('BOOLEANO', 'Booleano')], max_length=8)),
                ('invertida', models.BooleanField(default=False)),
                ('obligatoria', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='api.escalarespuesta')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='api.instrumentopsicologico')),
            ],
            options={
                'verbose_name': 'pregunta de instrumento',
                'verbose_name_plural': 'preguntas de instrumento',
                'db_table': 'saspel_pregunta_instrumento',
            },
        ),
        migrations.CreateModel(
            name='RangoInterpretacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('puntaje_minimo', models.IntegerField()),
                ('puntaje_maximo', models.IntegerField()),
                ('interpretacion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangos', to='api.instrumentopsicologico')),
            ],
            options={
                'verbose_name': 'rango de interpretación',
                'verbose_name_plural': 'rangos de interpretación',
                'db_table': 'saspel_rango_interpretacion',
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='api.aplicacioninstrumento')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='api.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='api.preguntainstrumento')),
            ],
            options={
                'verbose_name': 'respuesta a pregunta',
                'verbose_name_plural': 'respuestas a preguntas',
                'db_table': 'saspel_respuesta_pregunta',
            },
        ),
        migrations.CreateModel(
            name='ResultadoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_calculo', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplicacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado', to='api.aplicacioninstrumento')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='api.rangointerpretacion')),
            ],
            options={
                'verbose_name': 'resultado de instrumento',
                'verbose_name_plural': 'resultados de instrumentos',
                'db_table': 'saspel_resultado_instrumento',
            },
        ),
        migrations.AddConstraint(
            model_name='aplicacioninstrumento',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['INICIADA', 'FINALIZADA', 'ANULADA'])), name='saspel_aplicacion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='asignacioninstrumento',
            constraint=models.CheckConstraint(condition=models.Q(('origen__in', ['SISTEMA', 'PROFESIONAL'])), name='saspel_asig_instrumento_origen_valido'),
        ),
        migrations.AddConstraint(
            model_name='asignacioninstrumento',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA'])), name='saspel_asig_instrumento_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='opcionrespuesta',
            constraint=models.UniqueConstraint(fields=('escala', 'orden'), name='saspel_opcion_escala_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='opcionrespuesta',
            constraint=models.UniqueConstraint(fields=('escala', 'valor'), name='saspel_opcion_escala_valor_unico'),
        ),
        migrations.AddConstraint(
            model_name='preguntainstrumento',
            constraint=models.UniqueConstraint(fields=('instrumento', 'orden'), name='saspel_pregunta_instrumento_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='preguntainstrumento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_respuesta__in', ['ESCALA', 'TEXTO', 'NUMERO', 'BOOLEANO'])), name='saspel_pregunta_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='rangointerpretacion',
            constraint=models.CheckConstraint(condition=models.Q(('puntaje_minimo__lte', models.F('puntaje_maximo'))), name='saspel_rango_limites_validos'),
        ),
        migrations.AddConstraint(
            model_name='rangointerpretacion',
            constraint=models.UniqueConstraint(fields=('instrumento', 'nombre'), name='saspel_rango_instrumento_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='rangointerpretacion',
            constraint=models.UniqueConstraint(fields=('instrumento', 'orden'), name='saspel_rango_instrumento_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='respuestapregunta',
            constraint=models.UniqueConstraint(fields=('aplicacion', 'pregunta'), name='saspel_respuesta_aplicacion_pregunta_unica'),
        ),
    ]
