# Generated by Django 6.1 on 2026-09-07 17:40

"""Prepara las tablas de horarios habituales de psicólogos y citas.

No crea horarios ni citas de ejemplo. Este paso ya está aplicado; solo cambia
su explicación.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instrumentos_psicologicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada'), ('REPROGRAMADA', 'Reprogramada')], default='SOLICITADA', max_length=12)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprogramaciones', to='api.cita')),
                ('psicologo', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_psicologo', to=settings.AUTH_USER_MODEL)),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'saspel_cita',
                'indexes': [models.Index(fields=['psicologo', 'fecha_inicio', 'estado'], name='saspel_cita_psi_fecha_est_idx'), models.Index(fields=['trabajador', 'fecha_inicio', 'estado'], name='saspel_cita_trab_fecha_est_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='saspel_cita_fechas_validas'), models.CheckConstraint(condition=models.Q(('trabajador', models.F('psicologo')), _negated=True), name='saspel_cita_usuarios_distintos'), models.CheckConstraint(condition=models.Q(('cita_origen__isnull', True), models.Q(('cita_origen', models.F('pk')), _negated=True), _connector='OR'), name='saspel_cita_origen_distinto'), models.CheckConstraint(condition=models.Q(('estado__in', ['SOLICITADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA', 'RECHAZADA', 'REPROGRAMADA'])), name='saspel_cita_estado_valido'), models.CheckConstraint(condition=models.Q(('prioridad__in', ['BAJA', 'MEDIA', 'ALTA'])), name='saspel_cita_prioridad_valida')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_semanales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'disponibilidad de psicólogo',
                'verbose_name_plural': 'disponibilidades de psicólogos',
                'db_table': 'saspel_disponibilidad_psicologo',
                'indexes': [models.Index(fields=['psicologo', 'dia_semana', 'activo'], name='saspel_disp_psico_dia_act_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='saspel_disponibilidad_horas_validas'), models.CheckConstraint(condition=models.Q(('dia_semana__gte', 0), ('dia_semana__lte', 6)), name='saspel_disponibilidad_dia_valido'), models.UniqueConstraint(fields=('psicologo', 'dia_semana', 'hora_inicio', 'hora_fin'), name='saspel_disponibilidad_bloque_unico')],
            },
        ),
    ]
