from typing import Literal, Protocol
from uuid import UUID

from src.application.dto.instrument_content import ContentData, ContentFilters, ContentKind, ContentPage, ContentRecord


class ContentAdministration(Protocol):
    def list(self, kind: ContentKind, parent_id: UUID | None, filters: ContentFilters) -> ContentPage: ...
    def get(self, kind: ContentKind, parent_id: UUID | None, item_id: UUID) -> ContentRecord: ...
    def create(self, kind: ContentKind, parent_id: UUID | None, data: ContentData) -> ContentRecord: ...
    def edit(self, kind: ContentKind, parent_id: UUID | None, item_id: UUID, changes: dict) -> ContentRecord: ...
    def set_active(self, kind: ContentKind, parent_id: UUID | None, item_id: UUID, active: bool) -> ContentRecord: ...
    def move(self, kind: ContentKind, parent_id: UUID, item_id: UUID, direction: Literal['up', 'down']) -> ContentRecord: ...
